# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nicolas <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/08 19:41:05 by nicolas           #+#    #+#              #
#    Updated: 2024/03/17 11:57:34 by nicolas          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
# Latest version as of january 8 2024
version: '3.8'

# Networks
networks:
  transcendence:
    driver: bridge

# Volumes
volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/postgresql
      o: bind

# Services
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
    restart: unless-stopped
    networks:
      - transcendence
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend

  backend:
    container_name: backend
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendence

  database:
    container_name: database
    build:
      context: ./requirements/database
      dockerfile: Dockerfile
      args:
        PGDATA: ${PGDATA}
        PORT: ${DB_PORT}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendence
#    volumes:
#      - postgresql_data:/${PGDATA}
