# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nicolas <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/08 19:41:05 by nicolas           #+#    #+#              #
#    Updated: 2024/01/12 15:45:39 by mlaneyri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
# Latest version as of january 8 2024
version: '3.8'

# Networks
networks:
  transcendence:
    driver: bridge

# Volumes
volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/postgresql
      o: bind

# Services
services:

  backend:
    container_name: backend
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - "3450:3450"
    depends_on:
      - database

#  frontend:
#    container_name: frontend
#    build:
#      context: ./requirements/frontend
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    env_file:
#      - .env
#    networks:
#      - transcendence
#    ports:
#      - "8080:8080"

  database:
    container_name: database
    build:
      context: ./requirements/database
      dockerfile: Dockerfile
      args:
        PGDATA: ${PGDATA}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - postgresql_data:/${PGDATA}
