export enum MimeTypes {
    JPEG = 'image/jpeg',
    PNG = 'image/png',
    GIF = 'image/gif',
    PDF = 'application/pdf',
    TXT = 'text/plain',
    CSV = 'text/csv',
    HTML = 'text/html',
    JSON = 'application/json',
    XML = 'application/xml',
    ZIP = 'application/zip',
    MP3 = 'audio/mpeg',
    WAV = 'audio/wav',
    MP4 = 'video/mp4',
    AVI = 'video/x-msvideo',
    DOC = 'application/msword',
    DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    XLS = 'application/vnd.ms-excel',
    XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    PPT = 'application/vnd.ms-powerpoint',
    PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
}